#Packages
- name: Installing Compat-SAP-C++
  package:
    name: "{{ compat_packages }}"
    state: installed
  ignore_errors: yes

- name: Installing linux package repository for microsoft products
  command: rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
  ignore_errors: yes

- name: Installing java
  yum:
    name: java
    state: installed
  ignore_errors: yes

#Disks
# - name: vgextend /dev/rootvg /dev/sdc
#   command: vgextend /dev/rootvg /dev/sdc
#   ignore_errors: yes

# - name: lvextend -l +100%FREE /dev/rootvg/rootlv
#   command: lvextend -l +100%FREE /dev/rootvg/rootlv
#   ignore_errors: yes

# - name: resize2fs /dev/rootvg/rootlv
#   command: resize2fs /dev/rootvg/rootlv
#   ignore_errors: yes

