---
#Installs

#Create downloads folder
# - name: Create ~/Downloads directory
#   file:
#     path: ~/Downloads
#     state: directory
#     mode: '0777'
#     owner: root
#     group: root

- name: Create home/werner_deschryver/Downloads directory
  file:
    path: /home/werner_deschryver/Downloads
    state: directory
    mode: '0777'
    owner: root

- name: Create home/werner_deschryver/NetWeaver directory
  file:
    path: /home/werner_deschryver/NetWeaver
    state: directory
    mode: '0777'
    owner: root

- name: Download HANA files
  expect:
    command: rsync -alPvz flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/HANA-PLATFORM/51054623 /home/werner_deschryver/Downloads
    responses:
      (.*)password(.*): "Flexsostageadmin2020"
      (.*)connecting(.*): "yes"

- name: Download NetWeaver files
  expect:
    command: rsync -alPvz flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/NetWeaver /home/werner_deschryver/NetWeaver/
    responses:
      (.*)password(.*): "Flexsostageadmin2020"
      (.*)connecting(.*): "yes"

# - name: Change permissions inside /home/werner_deschryver/Downloads
#   file:
#     path: /home/werner_deschryver/Downloads
#     mode: '0777'
#     recurse: yes
