---
# Create directories to download installation files into
- name: Create /SAP directory
  file:
    path: /SAP
    state: directory
    mode: '0777'
    owner: root

- name: Create /SAP/HDB directory
  file:
    path: /SAP/HDB
    state: directory
    mode: '0777'
    owner: root

- name: Create /SAP/NetWeaver directory
  file:
    path: /SAP/NetWeaver
    state: directory
    mode: '0777'
    owner: root

# Check if HDB and NetWeaver directories are empty
# This is so the download tasks can be skipped when playbook is run multiple times
### CHECK OF RSYNC BY DEFAULT EXISTING FILES SKIPPED
### CHECK HOSTS FILE
### CAT FTP IP ADRESS >> HOSTS FILE
- name: Check if HDB files exist
  stat:
    path: /SAP/HDB/install.rsp
  register: HDB_data

- name: Check if NetWeaver files exist
  stat:
    path: /SAP/NetWeaver/parameters-gcp.params
  register: NetWeaver_data

# Downloads all the required files from FTP server
# TEST #sshpass -p 'Flexsostageadmin2020' rsync -e "ssh -o StrictHostKeyChecking=no" -alPvz flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/HANA-PLATFORM/51054623 /SAP/HDB
- name: Download HANA files
  command: sshpass -p 'Flexsostageadmin2020' rsync -e "ssh -o StrictHostKeyChecking=no" -alPvz flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/HANA-PLATFORM/51054623 /SAP/HDB
  async: 9999
  poll: 5
  when: not HDB_data.stat.exists

- name: Download NetWeaver files
  command: sshpass -p 'Flexsostageadmin2020' rsync -e "ssh -o StrictHostKeyChecking=no" -alPvz flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/NetWeaver /SAP/NetWeaver
  async: 9999
  poll: 5
  when: not NetWeaver_data.stat.exists

- name: Set permissions for /SAP
  file:
    path: /SAP
    mode: '0777'
    recurse: yes

# # Chmod permissions in /home directory so that 'hdblcm' can be executed
# - name: Change permission in /home
#   file:
#     path: /home
#     mode: '0777'

# Runs hdblcm in batchmode with configfile 'install.rsp'
# install.rsp currently works using a master password
- name: Installing SAP HANA Database
  shell: /SAP/HDB/51054623/DATA_UNITS/HDB_LCM_LINUX_X86_64/hdblcm -b --configfile=/SAP/HDB/51054623/install.rsp
  ignore_errors: yes
  register: config
- debug: var=config.stdout_lines

- name: Check if DATA_UNITS is already unzipped in NetWeaver
  stat:
    path: /SAP/NetWeaver/NetWeaver/DATA_UNITS
  register: DATA_UNITS_NW

- name: Unzip files inside /SAP/NetWeaver/NetWeaver
  unarchive:
    src: /SAP/NetWeaver/NetWeaver/51050829_3.ZIP
    dest: /SAP/NetWeaver/NetWeaver
  when: not DATA_UNITS_NW.stat.exists

- name: SAPCAR SWPM
  shell: /SAP/NetWeaver/NetWeaver/SAPCAR_1010-70006178.EXE -xvf /SAP/NetWeaver/NetWeaver/SWPM10SP31_2-20009701.SAR -R /SAP/NetWeaver/SWPM

#T #unzip 51050829_3.ZIP
#T #/NetWeaver/NetWeaver/SAPCAR_1010-70006178.EXE -xvf SWPM10SP31_2-20009701.SAR -R /SAP/NetWeaver/SWPM
# #/SAP/NetWeaver/SWPM/sapinst SAPINST_INPUT_PARAMETERS_URL=/SAP/NetWeaver/NetWeaver/parameters-gcp.params SAPINST_EXECUTE_PRODUCT_ID=NW_ABAP_OneHost:NW750.HDB.ABAP SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false