#Create NetWeaver install files dir
- name: Create /SAP/JAVA directory
  file:
    path: /SAP/NW_JAVA
    state: directory
    mode: '0777'
    owner: root

#Create NetWeaver install files dir
- name: Create /SAP/JAVA directory
  file:
    path: /SAP/NW_JAVA/51050829
    state: directory
    mode: '0777'
    owner: root    

#Download netweaver install files from ftp server
- name: Download NetWeaver files
  command: sshpass -p 'Flexsostageadmin2020' rsync -e "ssh -o StrictHostKeyChecking=no" -alPvz flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/NW_JAVA/ /SAP/NW_JAVA
  async: 9999
  poll: 5

#Sapcar SWPM
- name: SAPCAR SWPM
  shell: /SAP/NW_JAVA/SAPCAR_1010-70006178.EXE -xvf /SAP/NW_JAVA/SWPM10SP31_3-20009701.SAR -R /SAP/SWPM

# Add the usergroup sapinst so ownership of /Netweaver can be set to this group
- name: Add group sapinst
  command: groupadd sapinst
  ignore_errors: yes
  become: yes

  # Add the usergroup sapinst so ownership of /Netweaver can be set to this group
- name: Add group sapsys
  command: groupadd sapsys
  ignore_errors: yes
  become: yes

#Netweaver will be installed here
- name: Create /JAVA directory
  file:
    path: /JAVA
    group: sapinst
    state: directory
    owner: root
    mode: '0777'

#Export van bestanden
- name: Extracing NW JAVA based SW comp 
  unarchive:
    src: /SAP/NW_JAVA/51050829_3.ZIP
    dest: /SAP/NW_JAVA/51050829

- name: Extracing SAP Kernel 7.49 
  unarchive:
    src: /SAP/NW_JAVA/51051432_3.ZIP
    dest: /SAP/NW_JAVA/
  
- name: Extracing SAP ASE 16.0.04.00 SAP ASE 16.0.04.00
  unarchive:
    src: /SAP/NW_JAVA/51054690_1.ZIP
    dest: /SAP/NW_JAVA/

- name: Extracing SAP ASE SERVER
  command: tar -zxvf /SAP/NW_JAVA/ASESERV160004_0-20012052.TGZ -C /SAP/NW_JAVA

- name: Download Unrar
  command: wget -P /tmp https://www.rarlab.com/rar/rarlinux-x64-5.6.0.tar.gz

- name: Extracing Unrar 
  unarchive:
    src: /tmp/rarlinux-x64-5.6.0.tar.gz
    dest: /usr/local/bin

#Unrar rars
- name: extracting abap dir 1 
  command: /usr/local/bin/rar/unrar x /SAP/NW_JAVA/51050829_JAVA_part2.rar -d -y /SAP/NW_JAVA
  register: unrar
- debug: var=unrar.stdout_lines 

- name: extracting abap dir 2
  command: /usr/local/bin/rar/unrar x /SAP/NW_JAVA/51050829_LNG1_part2.rar -d -y /SAP/NW_JAVA
  register: unrar
- debug: var=unrar.stdout_lines 

#Bestanden aanpassen 
- name: Nofile hard limit toevoegen aan limits.conf
  command: echo @sapsys hard nofile 32800 >> /etc/security/limits.conf

- name: Nofile soft limit toevoegen aan limits.conf
  command: echo @sapsys soft nofile 32800 >> /etc/security/limits.conf

#Swapfile maken
- name: Nofile hard limit toevoegen aan limits.conf
  command: sudo fallocate -l 30G /swapfile

- name: Nofile hard limit toevoegen aan limits.conf
  command: sudo chmod 600 /swapfile

- name: Nofile hard limit toevoegen aan limits.conf
  command: sudo mkswap /swapfile

- name: Nofile hard limit toevoegen aan limits.conf
  command: sudo swapon /swapfile

- name: Nofile hard limit toevoegen aan limits.conf
  command: echo /swapfile swap swap defaults 0 0 >> /etc/fstab

- name: Nofile hard limit toevoegen aan limits.conf
  command: echo @sapsys hard nofile 32800 >> /etc/security/limits.conf

#Chdir to the required install directory for Netweaver & run the command to start installation
- name: Installing netweaver
  command: chdir=/JAVA /SAP/SWPM/sapinst SAPINST_INPUT_PARAMETERS_URL=/SAP/NeNW_JAVA/inifileAZURE_JAVA.params APINST_EXECUTE_PRODUCT_ID=NW_ABAP_OneHost:NW750.HDB.ABAP SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  register: config
- debug: var=config.stdout_lines 