---
#Installs
# - name: Installing Compat-SAP-C++
#   package:
#     name: "{{ compat_packages }}"
#     state: installed
#   ignore_errors: yes

# - name: Installing linux package repository for microsoft products
#   command: rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
#   ignore_errors: yes

# - name: Installing java
#   yum:
#     name: java
#     state: installed
#   ignore_errors: yes

# Disks
# - name: vgextend /dev/rootvg /dev/sdc
#   command: vgextend /dev/rootvg /dev/sdc
#   ignore_errors: yes

# - name: lvextend -l +100%FREE /dev/rootvg/rootlv
#   command: lvextend -l +100%FREE /dev/rootvg/rootlv
#   ignore_errors: yes

# - name: resize2fs /dev/rootvg/rootlv
#   command: resize2fs /dev/rootvg/rootlv
#   ignore_errors: yes

#Create downloads folder
# - name: Create /Downloads folder in root
#   file:
#     path: ~/Downloads
#     state: directory
#     mode: '0777'
#     owner: root
#     group: root

# Create directories to download installation files into
# - name: Create /SAP directory
#   file:
#     path: /SAP
#     state: directory
#     mode: '0777'
#     owner: root

# - name: Create /SAP/HDB directory
#   file:
#     path: /SAP/HDB
#     state: directory
#     mode: '0777'
#     owner: root

# - name: Create /SAP/NetWeaver directory
#   file:
#     path: /SAP/NetWeaver
#     state: directory
#     mode: '0777'
#     owner: root

# Downloads all the required files from FTP server
# - name: Download HANA files
#   command: sshpass -p 'Flexsostageadmin2020' rsync -e "ssh -o StrictHostKeyChecking=no" -alPvz flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/HANA-PLATFORM/51054623 /SAP/HDB
#   vars:
#     async: 9999
#     poll: 5

# - name: Download C++9
#   command: rpm --install /SAP/HDB/compat-sap-c++-9-9.1.1-2.3.el7_6.x86_64.rpm

# - name: Download NetWeaver files
#   command: sshpass -p 'Flexsostageadmin2020' rsync -e "ssh -o StrictHostKeyChecking=no" -alPvz flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/NetWeaver /SAP/NetWeaver
#   vars:
#     async: 9999
#     poll: 5

# - name: Set permissions for /SAP
#   file:
#     path: /SAP
#     mode: '0777'
#     recurse: yes

# - name: Installing SAP HANA Database
#   shell: cat /SAP/HDB/installAzure.rsp | /SAP/HDB/51054623/DATA_UNITS/HDB_LCM_LINUX_X86_64/hdblcm --read_password_from_stdin=xml --configfile=/SAP/HDB/installAzure.rsp -b
#   ignore_errors: yesexit
#   register: config
# - debug: var=config.stdout_lines

# - name: Unzip '51050829_3.ZIP' inside /SAP/NetWeaver/NetWeaver
#   unarchive:
#     src: /SAP/NetWeaver/NetWeaver/51050829_3.ZIP
#     dest: /SAP/NetWeaver/NetWeaver


#Download UNRAR
# - name: Downloading unrar

#   get_url:
#     url: https://www.rarlab.com/rar/rarlinux-x64-5.6.0.tar.gz
#     dest: /tmp
#     mode: '0777'

# #Extract unrar
# - name: extracing unrar 
#   command: tar -zxvf /tmp/rarlinux-x64-5.6.0.tar.gz
#   register: unrar
# - debug: var=unrar.stdout_lines 

# - name: Extracing Unrar 
#   unarchive:
#     src: /tmp/rarlinux-x64-5.6.0.tar.gz
#     dest: /usr/local/bin

# #Unrar rars
# - name: extracting abap dir 1 
#   command: /usr/local/bin/rar/unrar x /SAP/NetWeaver/NetWeaver/51052160_part2.rar
#   register: unrar
# - debug: var=unrar.stdout_lines 

# - name: extracting abap dir 2
#   command: /usr/local/bin/rar/unrar x /SAP/NetWeaver/NetWeaver/51052161_part2.rar
#   register: unrar
# - debug: var=unrar.stdout_lines 

- name: SAPCAR SWPM
  shell: /SAP/NetWeaver/NetWeaver/SAPCAR_1010-70006178.EXE -xvf /SAP/NetWeaver/NetWeaver/SWPM10SP31_2-20009701.SAR -R /SAP/NetWeaver/SWPM

#Netweaver will be installed here
- name: Create /Netweaver directory
  file:
    path: /Netweaver
    group: sapinst
    owner: root
    mode: '0777'

#Chdir to the required install directory for Netweaver & run the command to start installation
- name: Installing netweaver
  command: chdir=/Netweaver /SAP/NetWeaver/SWPM/sapinst SAPINST_INPUT_PARAMETERS_URL=/SAP/NetWeaver/NetWeaver/parameters-gcp.params SAPINST_EXECUTE_PRODUCT_ID=NW_ABAP_OneHost:NW750.HDB.ABAP SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  register: config
- debug: var=config.stdout_lines 
