---
# #Installs
# - name: Installing Compat-SAP-C++
#   package:
#     name: "{{ compat_packages }}"
#     state: installed
#   ignore_errors: yes

# - name: Installing linux package repository for microsoft products
#   command: rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
#   ignore_errors: yes

# - name: Installing java
#   yum:
#     name: java
#     state: installed
#   ignore_errors: yes

#Disks
# - name: vgextend /dev/rootvg /dev/sdc
#   command: vgextend /dev/rootvg /dev/sdc
#   ignore_errors: yes

# - name: lvextend -l +100%FREE /dev/rootvg/rootlv
#   command: lvextend -l +100%FREE /dev/rootvg/rootlv
#   ignore_errors: yes

# - name: resize2fs /dev/rootvg/rootlv
#   command: resize2fs /dev/rootvg/rootlv
#   ignore_errors: yes

# #Create downloads folder
# - name: Create /Downloads folder in root
#   file:
#     path: ~/Downloads
#     state: directory
#     mode: '0777'
#     owner: root
#     group: root

# # Create directories to download installation files into
# - name: Create /SAP directory
#   file:
#     path: /SAP
#     state: directory
#     mode: '0777'
#     owner: root

# - name: Create /SAP/HDB directory
#   file:
#     path: /SAP/HDB
#     state: directory
#     mode: '0777'
#     owner: root

# - name: Create /SAP/NetWeaver directory
#   file:
#     path: /SAP/NetWeaver
#     state: directory
#     mode: '0777'
#     owner: root

# # Downloads all the required files from FTP server
# - name: Download HANA files
#   command: sshpass -p 'Flexsostageadmin2020' rsync -e "ssh -o StrictHostKeyChecking=no" -alPvz flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/HANA-PLATFORM/51054623 /SAP/HDB
#   vars:
#     async: 9999
#     poll: 5

- name: Download C++9
  command: rpm --install /SAP/HDB/compat-sap-c++-9-9.1.1-2.3.el7_6.x86_64.rpm

- name: Download NetWeaver files
  command: sshpass -p 'Flexsostageadmin2020' rsync -e "ssh -o StrictHostKeyChecking=no" -alPvz flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/NetWeaver /SAP/NetWeaver
  vars:
    async: 9999
    poll: 5

- name: Installing SAP HANA Database
  shell: /SAP/HDB/51054623/DATA_UNITS/HDB_LCM_LINUX_X86_64/hdblcm -b --configfile=/SAP/HDB/51054623/installAzure.rsp
  ignore_errors: yesexit
  register: config
- debug: var=config.stdout_lines

- name: Unzip '51050829_3.ZIP' inside /SAP/NetWeaver/NetWeaver
  unarchive:
    src: /SAP/NetWeaver/NetWeaver/51050829_3.ZIP
    dest: /SAP/NetWeaver/NetWeaver

- name: SAPCAR SWPM
  shell: /SAP/NetWeaver/NetWeaver/SAPCAR_1010-70006178.EXE -xvf SWPM10SP31_2-20009701.SAR -R /SAP/NetWeaver/SWPM

- name: Unzip '51052160_part2.rar' inside /SAP/NetWeaver/NetWeaver
  unarchive:
    src: /SAP/NetWeaver/NetWeaver/51052160_part2.rar
    dest: /SAP/NetWeaver/NetWeaver

- name: Unzip '51052161_part2.rar' inside /SAP/NetWeaver/NetWeaver
  unarchive:
    src: /SAP/NetWeaver/NetWeaver/51052161_part2.rar
    dest: /SAP/NetWeaver/NetWeaver
# - name: Create home/azureuser/Downloads directory
#   file:
#     path: /home/azureuser/Downloads
#     state: directory
#     mode: '0777'
#     owner: root

# - name: Download Bin file
#   expect:
#     command: sftp flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/HXEDownloadManager_linux.bin /home/azureuser/Downloads
#     responses:
#       (.*)password(.*): "Flexsostageadmin2020"
#       (.*)connecting(.*): "yes"

# - name: Download Config file
#   expect:
#     command: sftp flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/install.rsp /home/azureuser/Downloads
#     responses:
#       (.*)password(.*): "Flexsostageadmin2020"
#       (.*)connecting(.*): "yes"

# - name: Download passwords file
#   expect:
#     command: sftp flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/install.rsp.xml /home/azureuser/Downloads
#     responses:
#       (.*)password(.*): "Flexsostageadmin2020"
#       (.*)connecting(.*): "yes"

# #Run HXEDownloadManager_linux.bin --ph {{ private_ip }} ...
# # - name: List contents of /home/werner_deschryver/Downloads
# #   command: ls /home/werner_deschryver/Downloads
# #   register: contents

# - name: Change permissions inside /home/werner_deschryver/Downloads
#   file:
#     path: /home/azureuser/Downloads
#     mode: '0777'
#     recurse: yes

# - name: Download hxe.tgz
#   command: /home/azureuser/Downloads/HXEDownloadManager_linux.bin --ph 10.0.2.4 --pp 8080 linuxx86_64 installer hxe.tgz
#   #when: contents.stdout == ""

# #Unarchive .tars
# - name: Make /HANA folder in root
#   file:
#     path: /HANA
#     state: directory
#     mode: '0777'
#     owner: root
#     group: root

# - name: Extract hxe.tgz
#   unarchive:
#     src: ~/Downloads/hxe.tgz
#     dest: /HANA

# - name: Copy configuration an and password file into HDBLCM and run in batch mode
#   shell: cat /home/azureuser/Downloads/install.rsp | /HANA/HANA_EXPRESS_20/DATA_UNITS/HDB_LCM_LINUX_X86_64/hdblcm --read_password_from_stdin=xml --configfile=/home/azureuser/Downloads/install.rsp -b
#   ignore_errors: yes
#   register: config
# - debug: var=config.stdout_lines