#Packages
- name: Installing Compat-SAP-C++
  package:
    name: "{{ compat_packages }}"
    state: installed
  ignore_errors: yes

- name: Installing linux package repository for microsoft products
  command: rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
  ignore_errors: yes