#Create NetWeaver install files dir
- name: Create /SAP/NetWeaver directory
  file:
    path: /SAP/NetWeaver
    state: directory
    mode: '0777'
    owner: root

#Check if NetWeaver install files have already been downloaded
- name: Check if NetWeaver files exist
  stat:
    path: /SAP/NetWeaver/parameters-gcp.params
  register: NetWeaver_data

#Download netweaver install files from ftp server
- name: Download NetWeaver files
  command: sshpass -p 'Flexsostageadmin2020' rsync -e "ssh -o StrictHostKeyChecking=no" -alPvz flexsostageadmin@51.103.26.163:/home/flexsostageadmin/ftp/NetWeaver /SAP/NetWeaver
  when: not NetWeaver_data.stat.exists
  async: 9999
  poll: 5

#Download UNRAR
- name: Downloading unrar
  get_url:
    url: https://www.rarlab.com/rar/rarlinux-x64-5.6.0.tar.gz
    dest: /tmp
    mode: '0777'

- name: extracting unrar 
  command: tar -zxvf /tmp/rarlinux-x64-5.6.0.tar.gz
  register: unrar
- debug: var=unrar.stdout_lines 

- name: extracting abap dir 1 
  command: /usr/local/bin/rar/unrar x /SAP/NetWeaver/NetWeaver/51052160_part2.rar
  register: unrar
- debug: var=unrar.stdout_lines 

- name: extracting abap dir 2
  command: /usr/local/bin/rar/unrar x /SAP/NetWeaver/NetWeaver/51052161_part2.rar
  register: unrar
- debug: var=unrar.stdout_lines 

#Sapcar SWPM
- name: SAPCAR SWPM
  shell: /SAP/NetWeaver/NetWeaver/SAPCAR_1010-70006178.EXE -xvf /SAP/NetWeaver/NetWeaver/SWPM10SP31_2-20009701.SAR -R /SAP/NetWeaver/SWPM

- name: Set permissions for /SAP
  file:
    path: /SAP
    mode: '0777'
    recurse: yes

# Add the usergroup sapinst so ownership of /Netweaver can be set to this group
- name: Add group sapinst
  command: groupadd sapinst
  ignore_errors: yes
  become: yes

#Netweaver will be installed here
- name: Create /ABAP directory
  file:
    path: /ABAP
    state: directory
    group: sapinst
    owner: root
    mode: '0777'

- name: Installing ABAP foundation
  command: chdir=/Netweaver /SAP/NetWeaver/SWPM/sapinst SAPINST_INPUT_PARAMETERS_URL=/SAP/SWMP/inifile_ABAP_Azure.params SAPINST_EXECUTE_PRODUCT_ID=NW_ABAP_OneHost:S4HANA1709.FNDN.HDB.ABAP SAPST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  register: config
- debug: var=config.stdout_lines