#Download UNRAR
- name: Downloading unrar
  get_url:
    url: https://www.rarlab.com/rar/rarlinux-x64-5.6.0.tar.gz
    dest: /tmp
    mode: '0777'

#Extract unrar
- name: extracing unrar 
  command: tar -zxvf /tmp/rarlinux-x64-5.6.0.tar.gz
  register: unrar
- debug: var=unrar.stdout_lines 

- name: Extracing Unrar 
  unarchive:
    src: /tmp/rarlinux-x64-5.6.0.tar.gz
    dest: /usr/local/bin

#Unrar rars
- name: extracting abap dir 1 
  command: /usr/local/bin/rar/unrar x /SAP/NetWeaver/NetWeaver/51052160_part2.rar
  register: unrar
- debug: var=unrar.stdout_lines 

- name: extracting abap dir 2
  command: /usr/local/bin/rar/unrar x /SAP/NetWeaver/NetWeaver/51052161_part2.rar
  register: unrar
- debug: var=unrar.stdout_lines 

#set perms
- name: Set permissions for /SAP
  file:
    path: /SAP
    mode: '0777'
    recurse: yes
